#!/bin/bash
ORG="StudioZeroOrg"
PROGRESS_FILE="worker_progress.md"

# Fetch progress strings
FORGE_PROG=$(grep "Forge" $PROGRESS_FILE | cut -d':' -f2-)
MICRO_PROG=$(grep "Micromaker" $PROGRESS_FILE | cut -d':' -f2-)
SCOUT_PROG=$(grep "Scout" $PROGRESS_FILE | cut -d':' -f2-)
SERV_PROG=$(grep "Serviceability" $PROGRESS_FILE | cut -d':' -f2-)

# Helper to comment on an issue
comment_issue() {
    REPO=$1
    ISSUE=$2
    PROGRESS=$3
    BLOCKER=$4
    MILESTONE=$5
    
    BODY="### Multi-Bot Status Update (5-Min Check-in)
**Latest Progress:** $PROGRESS
**Current Blocker:** $BLOCKER
**Next Milestone:** $MILESTONE

*Auto-generated by Manager Bot (Thu 🌝)*"

    gh issue comment $ISSUE -R $ORG/$REPO -b "$BODY"
}

# Comment on specific repo issues
comment_issue "ssg-apocalypse" 1 "$FORGE_PROG" "None" "Binary verification"
comment_issue "brainwave-visualizer" 1 "$MICRO_PROG" "None" "Asset optimization"
comment_issue "mqtt-privacy-filter" 1 "$SERV_PROG" "Integration testing" "Broadcaster validation"

# Comment on task tracking issues
comment_issue "tasks" 7 "$FORGE_PROG" "None" "Production build"
comment_issue "tasks" 6 "$MICRO_PROG" "None" "UI Polish"
comment_issue "tasks" 5 "$SERV_PROG" "None" "Filter stability"
comment_issue "tasks" 8 "$SCOUT_PROG" "None" "Final transcription"

